### ISSUE TITLE
AEROSPIKE_SERVER_ID contains domain

### ISSUE THREAD

**Issue by jacobrichard** [aerospike-community/aerospike-graphite#17]
The AEROSPIKE_SERVER_ID contains the domain for the machine in some cases. 

`us-west-1.prod.aerospike.aerospike01.myexampledomain.net.profiledata.storage-engine.scheduler-mode`

Since graphite will expand these into the tree, asgraphite should allow override of the hostname via an argument, or alternatively fix what appears to be a regression from #7 

For convenience I'll attach a PR that accomplishes this via a --hostname flag.

**Comment by whyrg** [comment]
#7 was not accepted. This is a better solution.

**Comment by whyrg** [comment]
Merged #18. Closing
