### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by dsw9742** [aerospike-community/aerospike-graphite#19]
Hi, it seems like there might be a few metrics missing from this plugin. 

I'm sure this is not an exhaustive list, but some of the metrics I've personally been unable to find:
  * batch_index_created_buffers
  * batch_index_destroyed_buffers
  * batch_index_unused_buffers
  * batch_index_huge_buffers
  * fabric_bulk_send_rate
  * fabric_bulk_recv_rate
  * fabric_ctrl_send_rate
  * fabric_ctrl_recv_rate
  * fabric_meta_send_rate
  * fabric_meta_recv_rate
  * fabric_rw_send_rate
  * fabric_rw_recv_rate
  * heap_active_kbytes
  * heap_mapped_kbytes
  * heap_allocated_kbytes
  * heap_efficiency_pct
  * heartbeat_received_foreign
  * heartbeat_received_self
  * uptime

I'm unsure if these are missing from [asgraphite](https://github.com/aerospike/aerospike-graphite) but figure that could be a contributing factor. Seems like this project has not been updated in quite a long time.

Any chance of getting an updated version that exposes current set of metrics?

**Comment by whyrg** [comment]
What is your Aerospike Server version and asgraphite version?

asgraphite does discovery of metrics through our `info` protocol. Any metrics that the server responds with gets parsed for formatting only. Any unrecognized lines are printed into the log. Asgraphite itself doesn't keep a list of *what is or isn't* a metric.

**Comment by dsw9742** [comment]
@whyrg Hi Richard, thanks for the quick response. 

Aerospike Server version is 3.15.0.2. 

As for the asgraphite version ... I'm not sure. I'm using the (Aerospike Prometheus Exporter)[https://github.com/alicebob/asprom], which indicates it "follows the logic from asgraphite." I had assumed it was wrapping the asgraphite library, but now I'm not so sure. Maybe it reimplements the asgraphite logic instead. Any chance you have a good idea how to go about validating that theory ... ?

**Comment by whyrg** [comment]
The Prometheus plugin keeps a small mapping of the initial [service metrics](https://github.com/alicebob/asprom/blob/master/stats.go#L11), as they need to differentiate counters and gauges. 

From my limited understanding of GoLang, it seems they only [parse the metrics](https://github.com/alicebob/asprom/blob/master/stats.go#L80) in this mapping, instead of applying said mapping to all discovered metrics.

Closing as this is a 3rd party issue.
