### ISSUE TITLE
Include Example Dashboards

### ISSUE THREAD

**Issue by mrwulf** [aerospike-community/aerospike-graphite#20]
It would be awesome to include some example grafana dashboards to consume the generated metrics. The dashboards should either be included here in the source (like https://github.com/aerospike/aerospike-elk/) or published to the grafana dashboard exchange (https://grafana.com/dashboards).

**Comment by whyrg** [comment]
This is under consideration.

**Comment by whyrg** [comment]
Dashboard added here as well as the dashboard exchange: https://grafana.com/dashboards/8074.

Enjoy!
