### ISSUE TITLE
Read ops_per_sec is not working under Aerospike version 5.3

### ISSUE THREAD

**Issue by jwong858** [aerospike-community/aerospike-graphite#26]
Hi,

We are running Aerospike version 5.3, but it seems asgraphite.py doesn't yield the read ops_per_sec metrics. Can you please check?

Your help is very much appreciated!

Thanks,

James

**Comment by jdogmcsteezy** [comment]
Hey James,

Can you be more specific about the metrics you are referring to?

**Comment by jwong858** [comment]
It's fixed. I just had to specify the latency arguments. Thanks.

**Comment by jdogmcsteezy** [comment]
I see you were talking about latency metrics.  Glad you got it figured out 👍🏼

**Comment by jwong858** [comment]
Actually it's not exactly fixed. I got the results that I wanted, but it
gave me an error. Please see below? I have tried various ways, but no luck.

# /opt/scripts/aerospike/asgraphite.py --once --stdout -l 'latencies:'
['latencies:hist={test}-benchmarks-write'
'latencies:hist={test}-benchmarks-read'] -n -U admin -P '*****' | grep
latency
-latency argument is in an incorrect format. Running with argument
"latencies:" instead.

Thanks,

James

**Comment by jdogmcsteezy** [comment]
Try this:
```
 /opt/scripts/aerospike/asgraphite.py --once --stdout -l 'latencies:' 'latencies:hist={test}-benchmarks-write' 'latencies:hist={test}-benchmarks-read' -n -U admin -P '*****'
```
The `[]` brackets point out that additional arguments are optional and should not be included in the command.

Also, make sure you have enabled read/write benchmark histograms with the following commands:
```
asinfo -v 'set-config:context=namespace;id=<NAMESPACE>;enable-benchmarks-write=true' -Uadmin -P****
asinfo -v 'set-config:context=namespace;id=<NAMESPACE>;enable-benchmarks-read=true' -Uadmin -P****
```

**Comment by jwong858** [comment]
No error, but no read latency metrics are generated, just like the defaults.

**Comment by jwong858** [comment]
I tried this too, but it doesn't give the read latency either.

/opt/scripts/aerospike/asgraphite.py --once --stdout -l 'latencies:' -l
'latencies:hist={nsCatalog}-benchmarks-write' -l
'latencies:hist={nsCatalog}-benchmarks-read' -n -U admin -P '*****'

**Comment by jwong858** [comment]
This gives me the read and latency, but errored out:

# /opt/scripts/aerospike/asgraphite.py --once --stdout --latency
'latencies:' "['latencies:hist={test}-benchmarks-write'
'latencies:hist={test}-benchmarks-read']" -n -U admin -P '****'
-latency argument is in an incorrect format. Running with argument
"latencies:" instead.

I know you told me not to include the "[]", but this seems to work.

**Comment by jdogmcsteezy** [comment]
hmmm . . . it could be that the `read` histograms do not have enough data to be generated on the `nsCatalog` namespace. It looks like the `test` namespace does have enough data to generate the `read` histograms.  Could you confirm that you have read records from `nsCatalog`?  I am guessing it takes about 20 read operations.   

FYI, To get just the `read` histogram  `'latencies:hist={test}-benchmarks-read'` is not needed but it does give more granularity on `read` operations.

**Comment by jwong858** [comment]
There is data, but anyway we still need metrics (even if it is 0) whether
or not there is data, otherwise the graphs will show no data. That's bad.
Management doesn't like that.

Also the namespace in this statement 'latencies:hist={test}-benchmarks-read' is
not taken literally. It will show all namespaces. I don't know why, but
this will save me time not having to gather the names of the namespaces in
each cluster. This will also work: 'latencies:hist=read'

Anyway, I am done with this issue - just ignore the -latency error.

Thanks for your help!

**Comment by jdogmcsteezy** [comment]
Let me be more clear, the metric will return 0 but if the server has just started it will need some read operation to take place before it will return anything.  After that, it will return metrics (even 0) as you require. Sorry about the confusion

Message back if you need any more help! :)

**Comment by jdogmcsteezy** [comment]
Bug found while investigating #27.  Should be fixed in the latest releases.
