### ISSUE TITLE
No latency metrics collected

### ISSUE THREAD

**Issue by shahdhr** [aerospike-community/aerospike-graphite#27]
I noticed that for my aerospike cluster I do not see latency stats. I checked the asgraphite.log file to find this error

Aerospike version: `5.0.0.10`
```
Unable to parse latency stats:
-1
'list' object has no attribute 'startswith'
```

Since the latency metrics include the read/write ops_per_sec metric which I want to monitor it would be great if I could receive some help on this ASAP. Thanks in advance.

**Comment by jdogmcsteezy** [comment]
Can you tell me what command you are running to start the service?

**Comment by shahdhr** [comment]
@jdogmcsteezy 
`python /opt/aerospike/bin/asgraphite -n -s -l latency: --interval 60 --prefix graph.aerospike.host. -g <graphite_host:port> --start`

**Comment by jdogmcsteezy** [comment]
There indeed was a bug.  I created two new releases [4.0.0](https://github.com/aerospike-community/aerospike-graphite/tree/4.0.0) and [3.0.1](https://github.com/aerospike-community/aerospike-graphite/tree/3.0.1).  Either will work if you are not using Ubuntu 14.

Please confirm that this fixes your problem.  Thanks for the bug report

**Comment by shahdhr** [comment]
@jdogmcsteezy That worked ✅ 
Thanks you so much!
